"""60-Day DAM Disclosure (NP3-966-ER): what every market participant offered, bid and was awarded, 60 days later.

One document per operating day: a zip of CSVs named ``60d_DAM_<table>-DD-MON-YY.csv``,
each one delivery date, all hours. The awards are the inputs to the flow check: the
cleared generation, storage and energy-only offer awards, energy bid awards and
point-to-point obligation awards that the DAM dispatched through its network. The
offer and bid curves and the ancillary service tables are parsed too; they are the
generation stack. The file name's date is the ``operating_date``; the header picks the
table, so a column ERCOT adds or renames is noticed, not guessed around.

Numbers (MW, prices, awards, limits, costs) are cast; identifiers (QSE, resource and
settlement point names, offer, bid and CRR IDs, flags and indicators) stay text.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime

import pyarrow as pa

from .table import Column, F, read_delimited, table_for_header

VERSION = 1

TABLES: dict[str, tuple[Column, ...]] = {
    "dam_60d_qse_self_arranged_as": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("Total Self-Arranged AS RegUp", F), Column("Total Self-Arranged AS RegDown", F), Column("Total Self-Arranged AS NonSpin", F), Column("Total Self-Arranged AS NSPNM", F), Column("Total Self-Arranged AS RRSPFR", F), Column("Total Self-Arranged AS RRSFFR", F), Column("Total Self-Arranged AS RRSUFR", F), Column("Total Self-Arranged AS ECRSSD", F), Column("Total Self-Arranged AS ECRSMD", F)),
    "dam_60d_gen_resource_data": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("DME"), Column("Resource Name"), Column("Resource Type"), Column("QSE submitted Curve-MW1", F), Column("QSE submitted Curve-Price1", F), Column("QSE submitted Curve-MW2", F), Column("QSE submitted Curve-Price2", F), Column("QSE submitted Curve-MW3", F), Column("QSE submitted Curve-Price3", F), Column("QSE submitted Curve-MW4", F), Column("QSE submitted Curve-Price4", F), Column("QSE submitted Curve-MW5", F), Column("QSE submitted Curve-Price5", F), Column("QSE submitted Curve-MW6", F), Column("QSE submitted Curve-Price6", F), Column("QSE submitted Curve-MW7", F), Column("QSE submitted Curve-Price7", F), Column("QSE submitted Curve-MW8", F), Column("QSE submitted Curve-Price8", F), Column("QSE submitted Curve-MW9", F), Column("QSE submitted Curve-Price9", F), Column("QSE submitted Curve-MW10", F), Column("QSE submitted Curve-Price10", F), Column("Start Up Hot", F), Column("Start Up Inter", F), Column("Start Up Cold", F), Column("Min Gen Cost", F), Column("HSL", F), Column("LSL", F), Column("Resource Status"), Column("Awarded Quantity", F), Column("Settlement Point Name"), Column("Energy Settlement Point Price", F), Column("RegUp Awarded", F), Column("RegUp MCPC", F), Column("RegDown Awarded", F), Column("RegDown MCPC", F), Column("RRSPFR Awarded", F), Column("RRSFFR Awarded", F), Column("RRSUFR Awarded", F), Column("RRS MCPC", F), Column("ECRSSD Awarded", F), Column("ECRS MCPC", F), Column("NonSpin Awarded", F), Column("NonSpin MCPC", F)),
    "dam_60d_generation_resource_as_offers": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("DME"), Column("Generation Resource Name"), Column("Multi-Hour Block Flag"), Column("BLOCK INDICATOR1"), Column("PRICE1 RRSPFR", F), Column("PRICE1 RRSFFR", F), Column("PRICE1 RRSUFR", F), Column("PRICE1 ECRS", F), Column("PRICE1 OFFEC", F), Column("PRICE1 ONLINE NONSPIN", F), Column("PRICE1 REGUP", F), Column("PRICE1 REGDOWN", F), Column("PRICE1 OFFLINE NONSPIN", F), Column("QUANTITY MW1", F), Column("BLOCK INDICATOR2"), Column("PRICE2 RRSPFR", F), Column("PRICE2 RRSFFR", F), Column("PRICE2 RRSUFR", F), Column("PRICE2 ECRS", F), Column("PRICE2 OFFEC", F), Column("PRICE2 ONLINE NONSPIN", F), Column("PRICE2 REGUP", F), Column("PRICE2 REGDOWN", F), Column("PRICE2 OFFLINE NONSPIN", F), Column("QUANTITY MW2", F), Column("BLOCK INDICATOR3"), Column("PRICE3 RRSPFR", F), Column("PRICE3 RRSFFR", F), Column("PRICE3 RRSUFR", F), Column("PRICE3 ECRS", F), Column("PRICE3 OFFEC", F), Column("PRICE3 ONLINE NONSPIN", F), Column("PRICE3 REGUP", F), Column("PRICE3 REGDOWN", F), Column("PRICE3 OFFLINE NONSPIN", F), Column("QUANTITY MW3", F), Column("BLOCK INDICATOR4"), Column("PRICE4 RRSPFR", F), Column("PRICE4 RRSFFR", F), Column("PRICE4 RRSUFR", F), Column("PRICE4 ECRS", F), Column("PRICE4 OFFEC", F), Column("PRICE4 ONLINE NONSPIN", F), Column("PRICE4 REGUP", F), Column("PRICE4 REGDOWN", F), Column("PRICE4 OFFLINE NONSPIN", F), Column("QUANTITY MW4", F), Column("BLOCK INDICATOR5"), Column("PRICE5 RRSPFR", F), Column("PRICE5 RRSFFR", F), Column("PRICE5 RRSUFR", F), Column("PRICE5 ECRS", F), Column("PRICE5 OFFEC", F), Column("PRICE5 ONLINE NONSPIN", F), Column("PRICE5 REGUP", F), Column("PRICE5 REGDOWN", F), Column("PRICE5 OFFLINE NONSPIN", F), Column("QUANTITY MW5", F)),
    "dam_60d_load_resource_data": (Column("Delivery Date"), Column("Hour Ending"), Column("Load Resource Name"), Column("Max Power Consumption for Load Resource", F), Column("Low Power Consumption for Load Resource", F), Column("RegUp Awarded", F), Column("RegUp MCPC", F), Column("RegDown Awarded", F), Column("RegDown MCPC", F), Column("RRSPFR Awarded", F), Column("RRSFFR Awarded", F), Column("RRSUFR Awarded", F), Column("RRS MCPC", F), Column("ECRSSD Awarded", F), Column("ECRSMD Awarded", F), Column("ECRS MCPC", F), Column("NonSpin Awarded", F), Column("NonSpin MCPC", F)),
    "dam_60d_load_resource_as_offers": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("DME"), Column("Load Resource Name"), Column("Multi-Hour Block Flag"), Column("BLOCK INDICATOR1"), Column("PRICE1 RRSPFR", F), Column("PRICE1 RRSFFR", F), Column("PRICE1 RRSUFR", F), Column("PRICE1 ECRS", F), Column("PRICE1 OFFEC", F), Column("PRICE1 ONLINE NONSPIN", F), Column("PRICE1 REGUP", F), Column("PRICE1 REGDOWN", F), Column("PRICE1 OFFLINE NONSPIN", F), Column("QUANTITY MW1", F), Column("BLOCK INDICATOR2"), Column("PRICE2 RRSPFR", F), Column("PRICE2 RRSFFR", F), Column("PRICE2 RRSUFR", F), Column("PRICE2 ECRS", F), Column("PRICE2 OFFEC", F), Column("PRICE2 ONLINE NONSPIN", F), Column("PRICE2 REGUP", F), Column("PRICE2 REGDOWN", F), Column("PRICE2 OFFLINE NONSPIN", F), Column("QUANTITY MW2", F), Column("BLOCK INDICATOR3"), Column("PRICE3 RRSPFR", F), Column("PRICE3 RRSFFR", F), Column("PRICE3 RRSUFR", F), Column("PRICE3 ECRS", F), Column("PRICE3 OFFEC", F), Column("PRICE3 ONLINE NONSPIN", F), Column("PRICE3 REGUP", F), Column("PRICE3 REGDOWN", F), Column("PRICE3 OFFLINE NONSPIN", F), Column("QUANTITY MW3", F), Column("BLOCK INDICATOR4"), Column("PRICE4 RRSPFR", F), Column("PRICE4 RRSFFR", F), Column("PRICE4 RRSUFR", F), Column("PRICE4 ECRS", F), Column("PRICE4 OFFEC", F), Column("PRICE4 ONLINE NONSPIN", F), Column("PRICE4 REGUP", F), Column("PRICE4 REGDOWN", F), Column("PRICE4 OFFLINE NONSPIN", F), Column("QUANTITY MW4", F), Column("BLOCK INDICATOR5"), Column("PRICE5 RRSPFR", F), Column("PRICE5 RRSFFR", F), Column("PRICE5 RRSUFR", F), Column("PRICE5 ECRS", F), Column("PRICE5 OFFEC", F), Column("PRICE5 ONLINE NONSPIN", F), Column("PRICE5 REGUP", F), Column("PRICE5 REGDOWN", F), Column("PRICE5 OFFLINE NONSPIN", F), Column("QUANTITY MW5", F), Column("NCLR Flag")),
    "dam_60d_energy_only_offers": (Column("Delivery Date"), Column("Hour Ending"), Column("Settlement Point"), Column("QSE Name"), Column("Energy Only Offer MW1", F), Column("Energy Only Offer Price1", F), Column("Energy Only Offer MW2", F), Column("Energy Only Offer Price2", F), Column("Energy Only Offer MW3", F), Column("Energy Only Offer Price3", F), Column("Energy Only Offer MW4", F), Column("Energy Only Offer Price4", F), Column("Energy Only Offer MW5", F), Column("Energy Only Offer Price5", F), Column("Energy Only Offer MW6", F), Column("Energy Only Offer Price6", F), Column("Energy Only Offer MW7", F), Column("Energy Only Offer Price7", F), Column("Energy Only Offer MW8", F), Column("Energy Only Offer Price8", F), Column("Energy Only Offer MW9", F), Column("Energy Only Offer Price9", F), Column("Energy Only Offer MW10", F), Column("Energy Only Offer Price10", F), Column("Energy Only Offer ID"), Column("Multi-Hour Block Indicator"), Column("Block/Curve indicator")),
    "dam_60d_energy_only_offer_awards": (Column("Delivery Date"), Column("Hour Ending"), Column("Settlement Point"), Column("QSE Name"), Column("Energy Only Offer Award in MW", F), Column("Settlement Point Price", F), Column("Offer ID")),
    "dam_60d_energy_bids": (Column("Delivery Date"), Column("Hour Ending"), Column("Settlement Point"), Column("QSE Name"), Column("Energy Only Bid MW1", F), Column("Energy Only Bid Price1", F), Column("Energy Only Bid MW2", F), Column("Energy Only Bid Price2", F), Column("Energy Only Bid MW3", F), Column("Energy Only Bid Price3", F), Column("Energy Only Bid MW4", F), Column("Energy Only Bid Price4", F), Column("Energy Only Bid MW5", F), Column("Energy Only Bid Price5", F), Column("Energy Only Bid MW6", F), Column("Energy Only Bid Price6", F), Column("Energy Only Bid MW7", F), Column("Energy Only Bid Price7", F), Column("Energy Only Bid MW8", F), Column("Energy Only Bid Price8", F), Column("Energy Only Bid MW9", F), Column("Energy Only Bid Price9", F), Column("Energy Only Bid MW10", F), Column("Energy Only Bid Price10", F), Column("Energy Only Bid ID"), Column("Multi-Hour Block Indicator"), Column("Block/Curve indicator")),
    "dam_60d_energy_bid_awards": (Column("Delivery Date"), Column("Hour Ending"), Column("Settlement Point"), Column("QSE Name"), Column("Energy Only Bid Award in MW", F), Column("Settlement Point Price", F), Column("Bid ID")),
    "dam_60d_ptp_obligation_option": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("Settlement Point Source"), Column("Settlement Point Sink"), Column("MW", F), Column("Price", F), Column("Offer ID"), Column("Multi-Hour Block Indicator"), Column("CRR ID")),
    "dam_60d_ptp_obligation_bids": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("Settlement Point Source"), Column("Settlement Point Sink"), Column("PtP Bid - MW", F), Column("PtP Bid - Price", F), Column("Bid ID"), Column("Multi-Hour Block Indicator")),
    "dam_60d_ptp_obligation_option_awards": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("Settlement Point Source"), Column("Settlement Point Sink"), Column("MW", F), Column("Price", F), Column("Offer ID"), Column("CRR ID")),
    "dam_60d_ptp_obligation_bid_awards": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("Settlement Point Source"), Column("Settlement Point Sink"), Column("PtP Bid Award - MW", F), Column("PtP Bid - Price", F), Column("Bid ID")),
    "dam_60d_esr_as_offers": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("DME"), Column("Resource Name"), Column("Multi-Hour Block Flag"), Column("BLOCK INDICATOR1"), Column("PRICE1 RRSPFR", F), Column("PRICE1 RRSFFR", F), Column("PRICE1 RRSUFR", F), Column("PRICE1 ECRS", F), Column("PRICE1 OFFEC", F), Column("PRICE1 ONLINE NONSPIN", F), Column("PRICE1 REGUP", F), Column("PRICE1 REGDOWN", F), Column("PRICE1 OFFLINE NONSPIN", F), Column("QUANTITY MW1", F), Column("BLOCK INDICATOR2"), Column("PRICE2 RRSPFR", F), Column("PRICE2 RRSFFR", F), Column("PRICE2 RRSUFR", F), Column("PRICE2 ECRS", F), Column("PRICE2 OFFEC", F), Column("PRICE2 ONLINE NONSPIN", F), Column("PRICE2 REGUP", F), Column("PRICE2 REGDOWN", F), Column("PRICE2 OFFLINE NONSPIN", F), Column("QUANTITY MW2", F), Column("BLOCK INDICATOR3"), Column("PRICE3 RRSPFR", F), Column("PRICE3 RRSFFR", F), Column("PRICE3 RRSUFR", F), Column("PRICE3 ECRS", F), Column("PRICE3 OFFEC", F), Column("PRICE3 ONLINE NONSPIN", F), Column("PRICE3 REGUP", F), Column("PRICE3 REGDOWN", F), Column("PRICE3 OFFLINE NONSPIN", F), Column("QUANTITY MW3", F), Column("BLOCK INDICATOR4"), Column("PRICE4 RRSPFR", F), Column("PRICE4 RRSFFR", F), Column("PRICE4 RRSUFR", F), Column("PRICE4 ECRS", F), Column("PRICE4 OFFEC", F), Column("PRICE4 ONLINE NONSPIN", F), Column("PRICE4 REGUP", F), Column("PRICE4 REGDOWN", F), Column("PRICE4 OFFLINE NONSPIN", F), Column("QUANTITY MW4", F), Column("BLOCK INDICATOR5"), Column("PRICE5 RRSPFR", F), Column("PRICE5 RRSFFR", F), Column("PRICE5 RRSUFR", F), Column("PRICE5 ECRS", F), Column("PRICE5 OFFEC", F), Column("PRICE5 ONLINE NONSPIN", F), Column("PRICE5 REGUP", F), Column("PRICE5 REGDOWN", F), Column("PRICE5 OFFLINE NONSPIN", F), Column("QUANTITY MW5", F)),
    "dam_60d_esr_data": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE"), Column("DME"), Column("Resource Name"), Column("Resource Type"), Column("QSE submitted Curve-MW1", F), Column("QSE submitted Curve-Price1", F), Column("QSE submitted Curve-MW2", F), Column("QSE submitted Curve-Price2", F), Column("QSE submitted Curve-MW3", F), Column("QSE submitted Curve-Price3", F), Column("QSE submitted Curve-MW4", F), Column("QSE submitted Curve-Price4", F), Column("QSE submitted Curve-MW5", F), Column("QSE submitted Curve-Price5", F), Column("QSE submitted Curve-MW6", F), Column("QSE submitted Curve-Price6", F), Column("QSE submitted Curve-MW7", F), Column("QSE submitted Curve-Price7", F), Column("QSE submitted Curve-MW8", F), Column("QSE submitted Curve-Price8", F), Column("QSE submitted Curve-MW9", F), Column("QSE submitted Curve-Price9", F), Column("QSE submitted Curve-MW10", F), Column("QSE submitted Curve-Price10", F), Column("Start Up Hot", F), Column("Start Up Inter", F), Column("Start Up Cold", F), Column("Min Gen Cost", F), Column("HSL", F), Column("LSL", F), Column("Resource Status"), Column("Awarded Quantity", F), Column("Settlement Point Name"), Column("Energy Settlement Point Price", F), Column("RegUp Awarded", F), Column("RegUp MCPC", F), Column("RegDown Awarded", F), Column("RegDown MCPC", F), Column("RRSPFR Awarded", F), Column("RRSFFR Awarded", F), Column("RRSUFR Awarded", F), Column("RRS MCPC", F), Column("ECRSSD Awarded", F), Column("ECRS MCPC", F), Column("NonSpin Awarded", F), Column("NonSpin MCPC", F)),
    "dam_60d_as_only_offers": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("Offer ID"), Column("AS Type"), Column("AS Only Offer MW1", F), Column("AS Only Offer Price1", F), Column("AS Only Offer MW2", F), Column("AS Only Offer Price2", F), Column("AS Only Offer MW3", F), Column("AS Only Offer Price3", F), Column("AS Only Offer MW4", F), Column("AS Only Offer Price4", F), Column("AS Only Offer MW5", F), Column("AS Only Offer Price5", F)),
    "dam_60d_as_only_awards": (Column("Delivery Date"), Column("Hour Ending"), Column("QSE Name"), Column("AS Type"), Column("Offer ID"), Column("Quantity1 Award", F), Column("Quantity2 Award", F), Column("Quantity3 Award", F), Column("Quantity4 Award", F), Column("Quantity5 Award", F), Column("Total Award", F), Column("MCPC", F)),
}

_MEMBER = re.compile(r"(?:^|/)60d_DAM_(?P<stem>.+)-(?P<day>\d\d-[A-Za-z]{3}-\d\d)\.csv$")


@dataclass(frozen=True)
class DisclosureMember:
    path: str
    format: str
    operating_date: date | None
    hour: None = None

    @property
    def is_parsed(self) -> bool:
        return self.format == "csv" and self.operating_date is not None


def classify_member(path: str) -> DisclosureMember | None:
    if path.endswith("/"):
        return None
    fmt = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    match = _MEMBER.search(path)
    day = datetime.strptime(match.group("day").upper(), "%d-%b-%y").date() if match else None
    return DisclosureMember(path, fmt, day)


def parse_member(member: DisclosureMember, data: bytes) -> dict[str, pa.Table]:
    table = table_for_header(data, TABLES, f"60-day DAM disclosure {member.operating_date}")
    return {table: read_delimited(data, TABLES[table], table)}
